"""Type definitions for MuseScore MCP."""

from .action_types import *

__all__ = [
    "ActionSequence",
    "GetScoreAction",
    "GetScoreParams",
    "AddNoteAction",
    "AddRestAction",
    "AddTupletAction",
    "AddLyricsAction",
    "AddInstrumentAction",
    "SetStaffMuteAction",
    "SetInstrumentSoundAction",
    "AppendMeasureAction",
    "DeleteSelectionAction",
    "GetCursorInfoAction",
    "GetCursorInfoParams",
    "GoToMeasureAction",
    "NextElementAction",
    "NextElementParams",
    "PrevElementAction",
    "PrevElementParams",
    "SelectCurrentMeasureAction",
    "InsertMeasureAction",
    "GoToFinalMeasureAction",
    "GoToBeginningOfScoreAction",
    "SetTimeSignatureAction",
    "UndoAction",
    "NextStaffAction",
    "PrevStaffAction",
    "SetTempoAction",
    "SetTempoParams",
    "SelectCustomRangeAction",
    "SyncStateToSelectionAction",
    "AddCursorElementAction",
    "AddCursorElementParams",
    "AddSlurAction",
    "AddTieAction",
    "AddHairpinAction",
    "AddHairpinParams",
    "ExportPdfAction",
    "ExportPdfParams",
    "SetVoiceAction",
    "SetVoiceParams",
]
